name: Trigger CI/CD
on:
  push:
    branches:
      - main
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger CI/CD
      run: |
        gh workflow run cicd.yml \
          --repo sianob/bp-deploy \
          --ref main \
          --field environment=staging \
          --field trigger=backend
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}